### PR TITLE
Add deep links, extract Apps page

### PR DESCRIPTION
**Pull request by davidyuk**
An alternative for #19.

### CODE REVIEW

**Comment by muxe** [comment]
I have some with the routing on this branch:

strange redirects after login:
* way to reproduce:
  * clean localStorage
  * go on http://localhost:8080
  * press login, create an account by either using the mnemonic phrase or pasting in an existing one
  * choose a password
* expected behaviour:
  * be redirected to the app browser and since its the first login the Quick ID Manager to pop up
* actual behaviour:
  * be redirected to /unlock with the quick id manager on top, if you close the quick id manager you still see the unlock (enter password) screen

no redirects on existing KS
* way to reproduce
  * create and unlock an account
  * you can see the KS in localStorage
  * close and re-open tab to identity manager
* expected:
  * be redirected to unlock screen and be able to unlock account
* actual:
  * still on welcome screen, only option to create new account

stranger thing is:
* the tests still work :)

Can you reproduce this? Let me know if you need more detailed explanation

**Comment by muxe** [comment]
also please edit this PR to merge into stage

**Comment by davidyuk** [comment]
I have found a better way to process initial path. For now, it preserves initial path even if keystore is not present.
Also, I have fixed redirection from Intro screen if keystore is present.

**Comment by muxe** [comment]
looks good, one small thing: there are still console errors because the id manager tries to generate addresses before the store is unlocked.
* have stored KS
* go on id-manager
* get redirected to /#/unlock
* see following error
```
TypeError: unexpected type [object Undefined], use Uint8Array
    at checkArrayTypes (nacl-fast.js?c880:2152)
    at Function.nacl.secretbox.open (nacl-fast.js?c880:2211)
    at Function.KeyStore._decryptString (keystore.js?9a45:151)
    at KeyStore.isDerivedKeyCorrect (keystore.js?9a45:128)
    at KeyStore.generateNewAddress (keystore.js?9a45:412)
    at Store.generateAddress (index.js?e3b1:214)
    at Array.wrappedActionHandler (vuex.esm.js?edaa:704)
    at Store.dispatch (vuex.esm.js?edaa:426)
    at Store.boundDispatch [as dispatch] (vuex.esm.js?edaa:332)
    at VueComponent.generateFirstAddress (IdManager.js?1b12:73)
```
The problem seems to be that generateFirstAddress() of IdManager.js gets called on unlock screen, but at this point there is no unlocked KS.

**Comment by davidyuk** [comment]
I propose to remove address generation on IdManager component creation because the user keystore is always locked on startup. Furthermore, necessary addresses are generated by calling of `restoreAddresses` store action at end of `initWeb3` action when the user unlocks an existing keystore. Also, `generateAddress` is called in `createKeystore` when the user creates new keystore and recovers an existing one.

**Pull request merged**
