### PR TITLE
Improve apps removing

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by dadaphl** [comment]
please describe what improved.

**Comment by davidyuk** [comment]
@dadaphl Sorry, I forgot to link pivotal tracker ticket in both directions:
https://www.pivotaltracker.com/story/show/158425002

**Comment by raymundjacobs** [comment]
@davidyuk Looks good! Only thing: can you position the Model Overlay on top?
screen shot 2018-06-25 at 12 29 16

**Comment by raymundjacobs** [comment]
@davidyuk The notification can stay, thanks for noticing. I've updated the screen in Zeplin: https://zpl.io/amBLn7r

**Comment by davidyuk** [comment]
@raymundjacobs @dadaphl please check again.

**Pull request merged**
