### PR TITLE
TX Confirm, trim amout

### PR DESCRIPTION
**Pull request by SamLife91**
trim amount in TX Confirm Dialog

### CODE REVIEW

**Comment by acdbaykal** [comment]
Hey @SamLife91, the currency symbol ("Æ") should stay on the same line.  But, within the identity manager this is the best one can do. Residue problems need to be solved  within the ae-amount component.
[](https://postimg.org/image/4q6klu3qf/)

**Comment by SamLife91** [comment]
@acdbaykal ok, i think i should create issue in aepp-components, and i have something on my mind how to resolve these type or problems on aepp-component level. is that ok to do ?

**Comment by acdbaykal** [comment]
@SamLife91, I just went ahead and did that just now. Would you review https://github.com/aeternity/aepp-components/pull/91 pls?

**Comment by muxe** [comment]
see https://github.com/aeternity/aepp-identity/pull/96

**Pull request closed without merging**
