### PR TITLE
My identities

### PR DESCRIPTION
**Pull request by Philip-Nunoo**
@davidyuk please this is the PR. Had to merge with the stage, and redo alot of stuff.

### CODE REVIEW

**Comment by davidyuk** [comment]
Ok. I will rebase it to the top of stage branch with removing of onboarding commits.

**Comment by muxe** [comment]
I get the following error in console:
```
webpack-internal:///9:1712 TypeError: this.swipeTo is not a function
    at VueComponent.mounted (webpack-internal:///230:56)
    at callHook (webpack-internal:///9:2890)
    at Object.insert (webpack-internal:///9:4085)
    at invokeInsertHook (webpack-internal:///9:5859)
    at VueComponent.patch [as __patch__] (webpack-internal:///9:6078)
    at VueComponent.Vue._update (webpack-internal:///9:2632)
    at VueComponent.updateComponent (webpack-internal:///9:2760)
    at Watcher.get (webpack-internal:///9:3110)
    at new Watcher (webpack-internal:///9:3099)
    at mountComponent (webpack-internal:///9:2767)
    at VueComponent.Vue$3.$mount (webpack-internal:///9:7890)
    at eval (webpack-internal:///349:116)
    at Object.<anonymous> (app.js:2938)
    at __webpack_require__ (app.js:660)
    at fn (app.js:86)
    at Object.<anonymous> (app.js:6337)
    at __webpack_require__ (app.js:660)
    at app.js:709
```

I get loads of warnings in console
```
[Vue warn]: Invalid prop: type check failed for prop "helpText". Expected String, got Number.

found in

---> <AeLabel>
       <IdManager> at src/components/IdManager/IdManager.vue
         <App> at src/App.vue
           <Root>
```
* In mobile view I can scroll horizontally a bit (thats why the inactive identities are not centered in the screenshot)
* When I scroll vertically the floating action button (add identity) scrolls with the content
* The activate button of inactive identities is always deactivated
screenshot from 2018-02-23 11-34-52

**Comment by Philip-Nunoo** [comment]
@davidyuk update

image

**Comment by davidyuk** [comment]
Close, because of the merged #90

**Pull request closed without merging**
