### PR TITLE
User id manager

### PR DESCRIPTION
**Pull request by Philip-Nunoo**
Replaces PR on https://github.com/aeternity/aepp-identity/pull/59

### CODE REVIEW

**Comment by muxe** [comment]
it seems your changes break the layout of the transfer screen (transfer to own identity)

screenshot from 2018-03-02 14-57-02

**Comment by muxe** [comment]
on mobile the crads aren't aligned properly, also the address should be displayed

screenshot from 2018-03-02 14-58-28

**Comment by Philip-Nunoo** [comment]
@muxe I noticed it's really not my commit. But something else. I've fixed the margin for s5 maybe we'd need to check everything well.

**Comment by acdbaykal** [comment]
@Philip-Nunoo 

you need to center the inactive identities.

[](https://postimg.org/image/rpg1uytez/)

**Comment by davidyuk** [comment]
Close, because of the merged #90

**Pull request closed without merging**
