### PR TITLE
Rewrite "postMessageHandler" as Vuex plugin

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by dadaphl** [comment]
@e-user I think that involves the signing rerouting part of the aepp-sdk. Please have a look whether  this will be compatible.

**Comment by davidyuk** [comment]
It is not supposed to be compatible with any new interface between the Base app and aepps, it is just refactoring of existing functionality.

**Comment by dadaphl** [comment]
@davidyuk the 'existing functionality' is made for the web3 provider `aeternity/id-manager-provider`. Is it really necessary to refactor code that dates back to the ethereum times?

We need something like this for sure! But should we not rather focus on making it work with the aepp-sdk?

**Comment by davidyuk** [comment]
The idea of this PR is that connection of store with frame messages should be implemented as Vuex plugin instead of a custom module, it doesn't depend on a particular api that will be accepted for communication between the Base app and aepps running inside.

**Pull request merged**
